name: amorfiapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_native_splash: ^2.4.1
  google_fonts: ^6.2.1
  text_marquee: ^0.0.2
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_storage: ^12.3.1
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  firebase_database: ^11.1.4
  provider: ^6.1.2
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^27.1.58
  intl: ^0.19.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.2.0
  permission_handler: ^12.0.0+1
  flutter_launcher_icons: ^0.14.4
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/pic/logoamorfiinvent.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/pic/logoamorfiinvent.png
